INSERT INTO `AUTHOR`(`AUTHORID`, `ANAME`) VALUES ("124312", "Jill A");
INSERT INTO `AUTHOR`(`AUTHORID`, `ANAME`) VALUES ("4212312", "Bill K");
INSERT INTO `AUTHOR`(`AUTHORID`, `ANAME`) VALUES ("4321", "Chill D");
INSERT INTO `AUTHOR`(`AUTHORID`, `ANAME`) VALUES ("43241", "Till J");
INSERT INTO `AUTHOR`(`AUTHORID`, `ANAME`) VALUES ("2321431", "Mill J");
