CREATE TABLE `CS_631`.`BOOK`(
    `DOCID` VARCHAR(50) NOT NULL,
    `ISBN` VARCHAR(100) NOT NULL,
    PRIMARY KEY(`DOCID`),
    CONSTRAINT BOOK_DOCID FOREIGN KEY BOOK(DOCID) REFERENCES DOCUMENT(DOCID) ON DELETE CASCADE
);
