CREATE TABLE `CS_631`.`BORROWS`(
    `BORNUMBER` VARCHAR(100) NOT NULL,
    `READERID` VARCHAR(100),
    `DOCID` VARCHAR(100),
    `COPYNO` VARCHAR(100),
    `LIBID` VARCHAR(100),
    `BDTIME` DATE NOT NULL,
    `RDTIME` DATE NOT NULL,
    PRIMARY KEY(`BORNUMBER`),
    CONSTRAINT BORROWS_READERID FOREIGN KEY RESERVES(READERID) REFERENCES READER(READERID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT BORROWS_DOCID FOREIGN KEY RESERVES(DOCID) REFERENCES COPY(DOCID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
