INSERT INTO `CHIEF_EDITOR`(`EDITOR_ID`, `ENAME`) VALUES ("E-123", "A Hill");
INSERT INTO `CHIEF_EDITOR`(`EDITOR_ID`, `ENAME`) VALUES ("E-43", "V Firhs");
INSERT INTO `CHIEF_EDITOR`(`EDITOR_ID`, `ENAME`) VALUES ("E-463", "B Mill");
INSERT INTO `CHIEF_EDITOR`(`EDITOR_ID`, `ENAME`) VALUES ("E-763", "G Hill");
INSERT INTO `CHIEF_EDITOR`(`EDITOR_ID`, `ENAME`) VALUES ("E-632", "B Chill");
