INSERT INTO `COPY`(`DOCID`, `COPYNO`, `LIBID`, `POSITION`) VALUES ("D124","1","L-123","N/A");
INSERT INTO `COPY`(`DOCID`, `COPYNO`, `LIBID`, `POSITION`) VALUES ("D13","1","L-323","N/A");
INSERT INTO `COPY`(`DOCID`, `COPYNO`, `LIBID`, `POSITION`) VALUES ("S532","1","L-143","N/A");
INSERT INTO `COPY`(`DOCID`, `COPYNO`, `LIBID`, `POSITION`) VALUES ("F82","1","L-1763","N/A");
INSERT INTO `COPY`(`DOCID`, `COPYNO`, `LIBID`, `POSITION`) VALUES ("Z452","1","L-5276","N/A");
