CREATE TABLE `CS_631`.`COPY`(
    `DOCID` VARCHAR(50) NOT NULL,
    `COPYNO` VARCHAR(100) NOT NULL,
    `LIBID` VARCHAR(100) NOT NULL,
    `POSITION` VARCHAR(100) NOT NULL,
    PRIMARY KEY(`DOCID`, `COPYNO`, `LIBID`),
    CONSTRAINT COPY_DOCID FOREIGN KEY COPY(DOCID) REFERENCES DOCUMENT(DOCID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT COPY_LIBID FOREIGN KEY COPY(LIBID) REFERENCES BRANCH(LIBID) ON DELETE CASCADE ON UPDATE CASCADE
)
