INSERT INTO `INV_EDITOR`(`DOCID`, `ISSUE_NO`, `IENAME`) VALUES ("D124","I_123","A");
INSERT INTO `INV_EDITOR`(`DOCID`, `ISSUE_NO`, `IENAME`) VALUES ("D13","I_32","A");
INSERT INTO `INV_EDITOR`(`DOCID`, `ISSUE_NO`, `IENAME`) VALUES ("S532","I_12","A");
INSERT INTO `INV_EDITOR`(`DOCID`, `ISSUE_NO`, `IENAME`) VALUES ("F82","I_1","A");
INSERT INTO `INV_EDITOR`(`DOCID`, `ISSUE_NO`, `IENAME`) VALUES ("Z452","I_11","A");
