CREATE TABLE `CS_631`.`INV_EDITOR`(
    `DOCID` VARCHAR(50),
    `ISSUE_NO` VARCHAR(100),
    `IENAME` VARCHAR(100) NOT NULL,
    PRIMARY KEY(`DOCID`, `ISSUE_NO`, `IENAME`),
    CONSTRAINT INV_EDITOR_DOCID FOREIGN KEY INV_EDITOR(DOCID) REFERENCES JOURNAL_ISSUE(DOCID) ON DELETE CASCADE ON UPDATE CASCADE
)
