INSERT INTO `JOURNAL_VOLUME`(`DOCID`, `JVOLUME`, `EDITOR_ID`) VALUES ("D124","Vol-1","E-123");
INSERT INTO `JOURNAL_VOLUME`(`DOCID`, `JVOLUME`, `EDITOR_ID`) VALUES ("D13","Vol-1","E-43");
INSERT INTO `JOURNAL_VOLUME`(`DOCID`, `JVOLUME`, `EDITOR_ID`) VALUES ("S532","Vol-1","E-463");
INSERT INTO `JOURNAL_VOLUME`(`DOCID`, `JVOLUME`, `EDITOR_ID`) VALUES ("F82","Vol-1","E-763");
INSERT INTO `JOURNAL_VOLUME`(`DOCID`, `JVOLUME`, `EDITOR_ID`) VALUES ("Z452","Vol-1","E-632");
