INSERT INTO `JOURNAL_ISSUE`(`DOCID`, `ISSUE_NO`, `SCOPE`) VALUES ("D124","I_123","History");
INSERT INTO `JOURNAL_ISSUE`(`DOCID`, `ISSUE_NO`, `SCOPE`) VALUES ("D13","I_32","SciFi");
INSERT INTO `JOURNAL_ISSUE`(`DOCID`, `ISSUE_NO`, `SCOPE`) VALUES ("S532","I_12","Math");
INSERT INTO `JOURNAL_ISSUE`(`DOCID`, `ISSUE_NO`, `SCOPE`) VALUES ("F82","I_1","English");
INSERT INTO `JOURNAL_ISSUE`(`DOCID`, `ISSUE_NO`, `SCOPE`) VALUES ("Z452","I_11","Health");
