INSERT INTO `PROCEEDINGS`(`DOCID`, `CDATE`, `CLOCATION`, `CEDITOR`) VALUES ("D124","2015-10-13","NJ","John A");
INSERT INTO `PROCEEDINGS`(`DOCID`, `CDATE`, `CLOCATION`, `CEDITOR`) VALUES ("D13","2015-10-06","NJ","Jill B");
INSERT INTO `PROCEEDINGS`(`DOCID`, `CDATE`, `CLOCATION`, `CEDITOR`) VALUES ("S532","2014-10-13","NJ","Ryan A");
INSERT INTO `PROCEEDINGS`(`DOCID`, `CDATE`, `CLOCATION`, `CEDITOR`) VALUES ("F82","2015-09-2","NJ","Rick A");
INSERT INTO `PROCEEDINGS`(`DOCID`, `CDATE`, `CLOCATION`, `CEDITOR`) VALUES ("Z452","2015-10-13","NJ","Sassy B");
