CREATE TABLE `CS_631`.`PROCEEDINGS`(
    `DOCID` VARCHAR(50) NOT NULL,
    `CDATE` DATE NOT NULL,
    `CLOCATION` VARCHAR(100) NOT NULL,
    `CEDITOR` VARCHAR(100) NOT NULL,
    PRIMARY KEY(`DOCID`),
    CONSTRAINT DOCID FOREIGN KEY PROCEEDINGS(DOCID) REFERENCES DOCUMENT(DOCID) ON DELETE CASCADE
);
