INSERT INTO `PUBLISHER`(`PUBLISHERID`, `PUBNAME`, `ADDRESS`) VALUES ("001","NJIT","001 New Street, Newark, NJ");
INSERT INTO `PUBLISHER`(`PUBLISHERID`, `PUBNAME`, `ADDRESS`) VALUES ("002", "PublishersRUs","243 Bleeker Street, Elizabeth, NY");
INSERT INTO `PUBLISHER`(`PUBLISHERID`, `PUBNAME`, `ADDRESS`) VALUES ("003", "Orange","534 Blue Lane, Monroe, Ohio");
INSERT INTO `PUBLISHER`(`PUBLISHERID`, `PUBNAME`, `ADDRESS`) VALUES ("004", "HiLife","653 Queen Road, Newark, NJ");
INSERT INTO `PUBLISHER`(`PUBLISHERID`, `PUBNAME`, `ADDRESS`) VALUES ("005", "PubCo","001 Orange Street, Trenton, NJ");
INSERT INTO `PUBLISHER`(`PUBLISHERID`, `PUBNAME`, `ADDRESS`) VALUES ("006", "Rutgers","452 Easton Ave, New Brunswick, NJ");
