CREATE TABLE `CS_631`.`READER`(
    `READERID` VARCHAR(50) NOT NULL,
    `RTYPE` VARCHAR(100) NOT NULL,
    `RNAME` VARCHAR(100) NOT NULL,
    `ADDRESS` VARCHAR(100) NOT NULL,
    PRIMARY KEY(`READERID`)
)
