CREATE TABLE `CS_631`.`RESERVES`(
    `RESNUMBER` VARCHAR(100) NOT NULL,
    `READERID` VARCHAR(100),
    `DOCID` VARCHAR(100),
    `COPYNO` VARCHAR(100),
    `LIBID` VARCHAR(100),
    `DTIME` DATE NOT NULL,
    PRIMARY KEY(`RESNUMBER`),
    CONSTRAINT RESERVES_READERID FOREIGN KEY RESERVES(READERID) REFERENCES READER(READERID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT RESERVES_DOCID FOREIGN KEY RESERVES(DOCID) REFERENCES COPY(DOCID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT RESERVES_COPYNO FOREIGN KEY RESERVES(COPYNO) REFERENCES COPY(COPYNO)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT RESERVES_LIBID FOREIGN KEY RESERVES(LIBID) REFERENCES COPY(LIBID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
